# Generated by Django 4.1 on 2022-08-15 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics')),
                ('phone_number', models.CharField(max_length=15)),
                ('doctor_registration_no', models.CharField(max_length=50)),
                ('specialized', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('nid', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('message', models.TextField(blank=True)),
                ('trx_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OldageHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='logo')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('license_no', models.CharField(max_length=50)),
                ('webaddress', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='logo')),
                ('icon', models.ImageField(upload_to='logo')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics')),
                ('designation', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('identification_number', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('highest_level_of_education', models.CharField(max_length=200)),
                ('oldageHome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.oldagehome')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='patient')),
                ('guardian_phone_number', models.CharField(blank=True, max_length=15)),
                ('guardian_nid', models.CharField(blank=True, max_length=18)),
                ('oldagehome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.oldagehome')),
            ],
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('disease_status', models.TextField()),
                ('treatment_status', models.TextField()),
                ('assigned_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.patient')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='oldageHome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.oldagehome'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
